### ISSUE TITLE
Question AAD B2C

### ISSUE THREAD

**Issue by tomadj** [Daniel-Krzyczkowski/Smart-Accounting#1]
Hello Daniel, 

Once again, great project ! 

I wonder about the use of AAD B2C : 

On the Lost-In-Azure-Cloud-Identity project you created two clients, One AAD and one AAD B2C. 
Here, it seems to me, that you have only one AAD B2C with an external identity provider to AAD for the employees. 

For my project, I hesitate between these two solutions. 

Do you have any recommendations regarding this ? 

Thank's 

Thomas

**Comment by Daniel-Krzyczkowski** [comment]
Hi Thomas,

Thank you for reaching out. Yes, in the Lost in Azure cloud identity project I use both identity services:
* Azure Active Directory
* Azure Active Directory B2C

Choice which one to use is strongly connected with the scenarios you would like to support in your solution. Could you please provide more details so I can help and provide accurate answers?

**Comment by tomadj** [comment]
Hi Daniel, 

Thank you for your time !

Here are some details (after having simplified) : 

**Summary**
It's for a web application to manage lease contracts between my company and customers. 
Front : Blazor WASM Backend : .Net Microservices ;)  

 **The different users**

_1) Internal to the company :_ 
- EMPLOYEE (salesman) 
- Admin

_2) External to the company :_
- CUSTOMER (renter)  
- BUSINESS PROVIDER
- maybe other concerned persons 

 **Use cases**
A Salesman (employee) can prepare a contract for the customer (renter) : 
- Connect with AAD 
- Create the contract
- Create the renter if not exist
- Manage/prepare the contract 
- Create or Init / an access account for the renter (invitation AAD B2C ?)    

A Renter can see his contracts : 
- Connect with AAD B2C 
- See contracts 
- Add requested documents..
- Sign contacts...

A business provider is like a Salesman but he is external to the company. he brings a case / a client :
- Connect with AAD B2C 
- initiate/create a contract

An administrator can create business providers 
- Connect with AAD 
- Create business provider
- Create or Init / an access account for the business provider(invitation AAD B2C ?)    

**Other information**

- Many of the app's screens will be similar with different permissions
- Users will handle the same things 
- I intended to use groups and app roles to manage rights, so it may be easier to use AAD B2C for all users ?? (
since AAD and AAD B2C are separate environments)

Hoping to have provided relevant informations

Thank you !

**Comment by Daniel-Krzyczkowski** [comment]
Hi Thomas,

Thank you for providing more details.
Just to summarize so we can confirm that I understood correctly:

In general there will be three different kinds of users:
* Internal - employees + administrator
* Partially external - business providers
* External - end users/customers/renters

All these three kinds of users will access the same application (Blazor) but with different level of authorization. It means that in the web application there will be authorization implemented to control access to different pages for different kinds of users.

If my assumptions above are correct, then I would recommend:

1. Using Azure Active Directory for:
* Internal users/employees
* Business providers - here I would recommend using either [external identities](https://www.microsoft.com/en-us/security/business/identity-access-management/azure-ad-external-identities) feature available in Azure AD or just guest users feature.
2. Using Azure AD B2C for end users/customers

With the assumption above you can federate Azure AD B2C tenant with Azure AD tenant (something I did in the Lost in Azure cloud identity project) and secure web application (Blazor) and API with Azure AD B2C. Customers will login with the accounts their created before and employees/business providers will login using their Azure AD accounts.
You have to also remember that Web APIs (microservices) have to also be secured with Azure AD B2C and authorization has to be implemented too. Of course in the portal app (Blazor) you will verify different roles/claims but you have to do the same in the microservices (to make sure that if someone will call them directly from Postman for instance, authorization will work properly).
I hope this information will help you.

**Comment by tomadj** [comment]
Hi Daniel,

I will test the to federate Azure AD B2C tenant with Azure AD tenant. 

Thank you very much !
